/*
 * Copyleft none (c) 2013 Aperture Laboratories, Inc. All rights free.
 *
 * @TROLLING_LICENSE
 * This file contains Original code of this,if you want pirate free, 
 * You are a pirate.
 *
 *
 *
 * The latest innovation in human-developing interaction. Our scientist have
 * shown in extensive tests that humans operating our fail project  on their
 * PC experience 33% more joy in life while smimultaneosly the likelihood of
 * being maimed or killed by falling pace debris is significantly reduced.
 * Also preliminary human trial indicate that it might offer some protection
 * against lethal dosages of gamma radiation and blows to  the head  with  a
 * rodlike object
 *
 * Kodizzle <not(dot)kodizzle(at)gmail(dot)com>
 * 
 * Problem: 
 * Each new term in the Fibonacci sequence is generated by adding the
 *  previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <stdlib.h>

#define __MAX		1000000 	// One million :D

#define MAX		__MAX * 4 	// 4 million :(
#define FB(n1,n2)	n1+n2
int *container = NULL;
int buff,x1,x2,size=0;
long int sum = 0;

void stampa_seq(int *v);

int main() {
	x1 = x2 = 1;
	buff = 0;
	container = (int*) realloc( container, (++size)*(sizeof(int)));
	container[size-1] = 1;
	do {
		container = (int*) realloc( container, (++size)*(sizeof(int)));
		container[size-1] = FB(x1,x2);
		x1 = x2;
		x2 = container[size-1];
		buff = container[size-1];
	} while(buff < MAX );
	
	stampa_seq(container); // for debug, don't try it at home
	for ( x1 = 1; x1 < size; x1++)
		sum += container[x1-1];
	printf("sum: %ld\n",sum);
	return 0;
}				

void stampa_seq(int *v) {
	printf("[ ");
        for ( x1 = 1; x1 < size; x1++) {
                printf(" %d, ",v[x1-1]);
        }
        printf("\b\b ]\n");
}
